CREATE TABLE "users" (
  "userid" SERIAL PRIMARY KEY,
  "username" VARCHAR(20),
  "email" TEXT,
  "password" TEXT
);

CREATE TABLE "scenarios" (
  "scenarioid" SERIAL PRIMARY KEY,
  "scenario1" text,
  "scenario2" text,
  "scenario3" text,
  "scenario4" text,
  "scenario5" text,
  "scenario6" text,
  "scenario7" text,
  "scenario8" text,
  "scenario9" text,
  "scenario10" text,
  "scenario11" text,
  "scenario12" text,
  "scenario13" text,
  "scenario14" text,
  "scenario15" text,
  "scenario16" text,
  "scenario17" text,
  "scenario18" text,
  "scenario19" text,
  "scenario20" text,
  "scenario21" text,
  "scenario22" text,
  "scenario23" text,
  "scenario24" text,
  "scenario25" text,
  "scenario26" text,
  "scenario27" text,
  "scenario28" text,
  "scenario29" text,
  "scenario30" text,
  "scenario31" text,
  "scenario32" text,
  "scenario33" text,
  "scenario34" text,
  "scenario35" text,
  "scenario36" text,
  "scenario37" text,
  "scenario38" text,
  "scenario39" text,
  "scenario40" text,
  "scenario41" text,
  "scenario42" text,
  "scenario43" text,
  "scenario44" text,
  "scenario45" text,
  "scenario46" text,
  "scenario47" text,
  "scenario48" text,
  "scenario49" text,
  "scenario50" text,
  "scenario51" text,
  "scenario52" text,
  "scenario53" text,
  "scenario54" text,
  "scenario55" text,
  "scenario56" text,
  "scenario57" text,
  "scenario58" text,
  "scenario59" text,
  "scenario60" text,
  "scenario61" text,
  "scenario62" text,
  "scenario63" text,
  "scenario64" text,
  "scenario65" text,
  "scenario66" text,
  "scenario67" text,
  "scenario68" text,
  "scenario69" text,
  "scenario70" text,
  "scenario71" text,
  "scenario72" text,
  "scenario73" text,
  "scenario74" text,
  "scenario75" text,
  "scenario76" text,
  "scenario77" text,
  "scenario78" text,
  "scenario79" text,
  "scenario80" text,
  "scenario81" text,
  "scenario82" text,
  "scenario83" text,
  "scenario84" text,
  "scenario85" text,
  "scenario86" text,
  "scenario87" text,
  "scenario88" text,
  "scenario89" text,
  "scenario90" text,
  "scenario91" text,
  "scenario92" text,
  "scenario93" text,
  "scenario94" text,
  "scenario95" text
);

CREATE TABLE "achievements" (
  "achievementsid" SERIAL PRIMARY KEY,
  "cityrule_militaristic" TEXT,
  "cityrule_economic" text,
  "voice_freed" text,
  "voice_silenced" text,
  "drake_aided" text,
  "drake_slain" text,
  "dead_invade" text,
  "mechant_flees" text,
  "artifact_recovered" text,
  "artifact_lost" text,
  "artifact_cleansed" text,
  "citryrule_demonic" text,
  "ancient_technology" text,
  "end_gloom" text,
  "end_corruption" text,
  "end_invasion" text,
  "edge_darkness" text,
  "rift_neutralized" text,
  "power_enhancement" text,
  "water_breathing" text,
  "annihilation_order" text
);

CREATE TABLE "citydeck" (
  "citydeckid" SERIAL PRIMARY KEY,
  "card1" text,
  "card2" text,
  "card3" text,
  "card4" text,
  "card5" text,
  "card6" text,
  "card7" text,
  "card8" text,
  "card9" text,
  "card10" text,
  "card11" text,
  "card12" text,
  "card13" text,
  "card14" text,
  "card15" text,
  "card16" text,
  "card17" text,
  "card18" text,
  "card19" text,
  "card20" text,
  "card21" text,
  "card22" text,
  "card23" text,
  "card24" text,
  "card25" text,
  "card26" text,
  "card27" text,
  "card28" text,
  "card29" text,
  "card30" text,
  "card31" text,
  "card32" text,
  "card33" text,
  "card34" text,
  "card35" text,
  "card36" text,
  "card37" text,
  "card38" text,
  "card39" text,
  "card40" text,
  "card41" text,
  "card42" text,
  "card43" text,
  "card44" text,
  "card45" text,
  "card46" text,
  "card47" text,
  "card48" text,
  "card49" text,
  "card50" text,
  "card51" text,
  "card52" text,
  "card53" text,
  "card54" text,
  "card55" text,
  "card56" text,
  "card57" text,
  "card58" text,
  "card59" text,
  "card60" text,
  "card61" text,
  "card62" text,
  "card63" text,
  "card64" text,
  "card65" text,
  "card66" text,
  "card67" text,
  "card68" text,
  "card69" text,
  "card70" text,
  "card71" text,
  "card72" text,
  "card73" text,
  "card74" text,
  "card75" text,
  "card76" text,
  "card77" text,
  "card78" text,
  "card79" text,
  "card80" text,
  "card81" text
);

CREATE TABLE "roaddeck" (
  "roaddeckid" SERIAL PRIMARY KEY,
  "card1" text,
  "card2" text,
  "card3" text,
  "card4" text,
  "card5" text,
  "card6" text,
  "card7" text,
  "card8" text,
  "card9" text,
  "card10" text,
  "card11" text,
  "card12" text,
  "card13" text,
  "card14" text,
  "card15" text,
  "card16" text,
  "card17" text,
  "card18" text,
  "card19" text,
  "card20" text,
  "card21" text,
  "card22" text,
  "card23" text,
  "card24" text,
  "card25" text,
  "card26" text,
  "card27" text,
  "card28" text,
  "card29" text,
  "card30" text,
  "card31" text,
  "card32" text,
  "card33" text,
  "card34" text,
  "card35" text,
  "card36" text,
  "card37" text,
  "card38" text,
  "card39" text,
  "card40" text,
  "card41" text,
  "card42" text,
  "card43" text,
  "card44" text,
  "card45" text,
  "card46" text,
  "card47" text,
  "card48" text,
  "card49" text,
  "card50" text,
  "card51" text,
  "card52" text,
  "card53" text,
  "card54" text,
  "card55" text,
  "card56" text,
  "card57" text,
  "card58" text,
  "card59" text,
  "card60" text,
  "card61" text,
  "card62" text,
  "card63" text,
  "card64" text,
  "card65" text,
  "card66" text,
  "card67" text,
  "card68" text,
  "card69" text
);

CREATE TABLE party (
  "partyid" SERIAL PRIMARY KEY,
  "partyname" VARCHAR(30),
  "scenarioid" integer references scenarios(scenarioid),
  "achievementsid" integer references achievements(achievementsid),
  "citydeckid" integer references citydeck(citydeckid),
  "roaddeckid" integer references roaddeck(roaddeckid)
);


SELECT * FROM scenarios JOIN party ON scenarios.scenarioid = party.scenarioid;
SELECT * FROM achievements JOIN party ON achievements.achievementsid = party.achievementsid;
SELECT * FROM citydeck JOIN party ON citydeck.citydeckid = party.citydeckid;
SELECT * FROM roaddeck JOIN party ON roaddeck.roaddeckid = party.roaddeckid;

CREATE TABLE usersparties (
userid integer references users(userid),
partyid integer references party(partyid),
characterchoice text,
charactername text
);
SELECT * FROM users JOIN usersparties ON users.userid = usersparties.userid;
SELECT * FROM party JOIN usersparties ON party.partyid = usersparties.partyid;

SELECT * FROM users;
SELECT * FROM usersparties;
SELECT * FROM party;
SELECT * FROM scenarios;
SELECT * FROM achievements;
SELECT * FROM citydeck;
SELECT * FROM roaddeck;